#!/usr/bin/env bash

# shellcheck shell=bash

# ``````````````````````````````````````````````````````````````````````````````
# Function name: GetTorProcess()
#
# Description:
#   Get info about tor process.
#
# Usage:
#   GetTorProcess
#
# Examples:
#   GetTorProcess
#

function GetTorProcess() {

  # shellcheck disable=SC2034
  local _FUNCTION_ID="GetTorProcess"
  local _STATE=0

  # shellcheck disable=SC2034,SC2154
  _tor_proc_id=$(echo "$_tproc" | awk '{print $1}')
  # shellcheck disable=SC2034
  #_tor_proc_config=$(echo "$_tproc" | awk '{print $7}')
  _tor_proc_config=$(echo "$_tproc" | awk '{print $9}')
  # shellcheck disable=SC2034
  #_tor_proc_socks=$(echo "$_tproc" | awk '{print $13}')
  _tor_proc_socks=$(echo "$_tproc" | awk '{print $15}'| cut -d ':' -f 2)
  # shellcheck disable=SC2034
  #_tor_proc_control=$(echo "$_tproc" | awk '{print $15}')
  _tor_proc_control=$(echo "$_tproc" | awk '{print $17}')
  # shellcheck disable=SC2034
  #_tor_prod_data_dir=$(echo "$_tproc" | awk '{print $19}')
  _tor_prod_data_dir=$(echo "$_tproc" | awk '{print $21}')

  return $_STATE

}
